version: '3.8'
services: 
    flask_frontend:
        build: .
        volumes: 
            - .:/usr/src/app/
        ports: 
            - 8890:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1

